#!/bin/sh

RELEASE="0m12"

DESTDIR=/export/tribblix/dist

ISODIR=/var/tmp
ISONAME=tribblix-${RELEASE}.iso

case $# in
1)
	DESTDIR=${DESTDIR}.$1
	ISONAME=tribblix-${RELEASE}-${1}.iso
	;;
esac

/usr/bin/mkisofs -o ${ISODIR}/${ISONAME} -b boot/grub/stage2_eltorito \
	-c .catalog -volset `cat ${DESTDIR}/.volsetid` \
	-no-emul-boot -boot-load-size 4 -boot-info-table -N -l -R -U \
        -allow-multidot -no-iso-translate -cache-inodes -d -D \
	-V "Tribblix${RELEASE}" ${DESTDIR}

/bin/ls -lh ${ISODIR}/${ISONAME}
