#!/bin/sh

THOME=${THOME:-/packages/localsrc/Tribblix}

DESTDIR=/export/tribblix/dist
ISODIR=/var/tmp
ISOROOT="tribtest"
RELEASE="beta"

#
# flags
# -D destdir -> DESTDIR
# -I isodir -> ISODIR
# -N iso root name -> ISOROOT
# -R release string -> RELEASE
#
while getopts "D:I:N:R:" opt; do
    case $opt in
        D)
	    DESTDIR="$OPTARG"
	    ;;
        I)
	    ISODIR="$OPTARG"
	    ;;
        N)
	    ISOROOT="$OPTARG"
	    ;;
        R)
	    RELEASE="$OPTARG"
	    ;;
    esac
done
shift $((OPTIND-1))

case `uname -p` in
sparc)
	ISOROOT="${ISOROOT}-sparc"
	;;
esac

ISONAME=${ISOROOT}-${RELEASE}.iso
case $# in
1)
	DESTDIR=${DESTDIR}.$1
	ISONAME=${ISOROOT}-${RELEASE}-${1}.iso
	;;
esac

#
CDBOOT="boot/cdboot"
UEFIBOOT="boot/efiboot.img"

case `uname -p` in
sparc)
	/usr/bin/dd if="${DESTDIR}/platform/sun4v/lib/fs/hsfs/bootblk" \
            of="${DESTDIR}/boot/hsfs.bootblock" \
            bs=1b oseek=1 count=15 conv=sync 2> /dev/null

	/usr/bin/mkisofs -o ${ISODIR}/${ISONAME} -G "${DESTDIR}/boot/hsfs.bootblock" \
	-B ... -N -l -ldots -R -D -volset `cat ${DESTDIR}/.volsetid` \
	-V "Tribblix${RELEASE}" ${DESTDIR}

	;;
i386)
	/usr/bin/mkisofs -N -l -R -U -d -D -o ${ISODIR}/${ISONAME} \
	-V "Tribblix${RELEASE}" \
        -allow-multidot -no-iso-translate -cache-inodes \
	-c .catalog -volset `cat ${DESTDIR}/.volsetid` \
	-b ${CDBOOT} -no-emul-boot -boot-load-size 4 -boot-info-table \
	-eltorito-alt-boot -eltorito-platform efi \
	-eltorito-boot ${UEFIBOOT} -no-emul-boot \
	${DESTDIR}

	${THOME}/tribblix-build/hybridize-iso ${ISODIR}/${ISONAME} ${DESTDIR}

	;;
esac

/bin/ls -lh ${ISODIR}/${ISONAME}
