#!/bin/sh

THOME=/packages/localsrc/Tribblix
TPKGDIR=${THOME}/pkgs
PKGDIR=${THOME}/oi-pkgs-0.8/pkgs
IPKGDIR=${THOME}/illumos-pkgs-m15/pkgs
DESTDIR=/export/tribblix/dist
FDEFAULT=${THOME}/tribblix-build/pkg.default

ILVER="0.15.0"
OIVER="0.8o"

#
# this is the base install, plus we add TRIBsys-install-media-internal
# to the iso
#
PKGLIST=${THOME}/overlays/base.pkgs

case $# in
1)
	DESTDIR=${DESTDIR}.$1
	PKGLIST=${PKGLIST}.$1
	;;
esac

#
# first verify
#
VALID=yes
for mypkg in `cat ${PKGLIST}` TRIBsys-install-media-internal
do
  THISVER="XXX"
  PKGI=${THOME}/build/${mypkg}/pkginfo
  if [ -f ${PKGI} ]; then
      THISVER=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI | sed 's="==g'`
  fi
  if [ -f ${TPKGDIR}/${mypkg}.${THISVER}.pkg ]; then
      echo "Installing $mypkg from Tribblix"
  elif [ -f ${TPKGDIR}/${mypkg}.pkg ]; then
      echo "Installing unversioned $mypkg from Tribblix"
  elif [ -f ${IPKGDIR}/${mypkg}.${ILVER}.pkg ]; then
      echo "Installing $mypkg from Illumos"
  elif [ -f ${IPKGDIR}/${mypkg}.pkg ]; then
      echo "Installing $mypkg from Illumos"
  elif [ -f ${PKGDIR}/${mypkg}.pkg ]; then
      echo "Installing $mypkg from OpenIndiana"
  else
      echo "ERROR: package $mypkg not found"
      VALID=no
  fi
done

if [ "X$VALID" = "Xno" ]; then
    echo "ERROR: missing packages, install aborted"
    exit 1
fi

if [ ! -d ${DESTDIR} ]; then
    echo "ERROR: Target destination ${DESTDIR} not found, install aborted"
    exit 1
fi

#
# building Tribblix in a zone on Tribblix, this needs to be created first
# but most everything fails in a zone, so don't bother
#
#mkdir -p ${DESTDIR}/var/sadm/install
#
# now install
#
for mypkg in `cat ${PKGLIST}` TRIBsys-install-media-internal
do
  THISVER="XXX"
  PKGI=${THOME}/build/${mypkg}/pkginfo
  if [ -f ${PKGI} ]; then
      THISVER=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI | sed 's="==g'`
  fi
  if [ -f ${TPKGDIR}/${mypkg}.${THISVER}.pkg ]; then
    pkgadd -a ${FDEFAULT} -R $DESTDIR -d ${TPKGDIR}/${mypkg}.${THISVER}.pkg $mypkg
  elif [ -f ${TPKGDIR}/${mypkg}.pkg ]; then
    pkgadd -a ${FDEFAULT} -R $DESTDIR -d ${TPKGDIR}/${mypkg}.pkg $mypkg
  elif [ -f ${IPKGDIR}/${mypkg}.${ILVER}.pkg ]; then
    pkgadd -a ${FDEFAULT} -R $DESTDIR -d ${IPKGDIR}/${mypkg}.${ILVER}.pkg $mypkg
  elif [ -f ${IPKGDIR}/${mypkg}.pkg ]; then
    pkgadd -a ${FDEFAULT} -R $DESTDIR -d ${IPKGDIR}/${mypkg}.pkg $mypkg
  else
    pkgadd -a ${FDEFAULT} -R $DESTDIR -d ${PKGDIR}/${mypkg}.pkg $mypkg
  fi
done

#
# need to mark the base overlay as installed
#
mkdir -p ${DESTDIR}/var/sadm/overlays/installed
touch ${DESTDIR}/var/sadm/overlays/installed/base
