#!/bin/ksh
#
# build a bootable iso
#

THOME=${THOME:-/packages/localsrc/Tribblix}
TBHOME=${THOME}/tribblix-build
DESTTOP=/export/tribblix
DESTDIR=${DESTTOP}/dist
TRIBVER="OmniTribblix 0.23lx.1"

case $# in
1)
	DESTDIR=${DESTDIR}.$1
	;;
esac

#
# fix the image
#
echo "Reset initial files"
if [ -x /usr/gnu/bin/md5sum ]; then
    echo ${TRIBVER} | /usr/gnu/bin/md5sum - | awk '{print $1}' > ${DESTDIR}/.volsetid
else
    echo ${TRIBVER} | openssl md5 | awk '{print $NF}' > ${DESTDIR}/.volsetid
fi
#
# ensure /etc/system is clean
#
grep -v '^set' /etc/system > ${DESTDIR}/etc/system
#
echo "tribblix" > ${DESTDIR}/etc/nodename
rm -f ${DESTDIR}/etc/svc/profile/generic.xml
rm -f ${DESTDIR}/etc/svc/profile/platform.xml
rm -f ${DESTDIR}/etc/svc/profile/name_service.xml
if [ -f ${DESTTOP}/prebuilt/generic_live.xml ]; then
    cp ${DESTTOP}/prebuilt/generic_live.xml ${DESTDIR}/etc/svc/profile
    ln -s generic_live.xml ${DESTDIR}/etc/svc/profile/generic.xml
else
    ln -s generic_limited_net.xml ${DESTDIR}/etc/svc/profile/generic.xml
fi
ln -s platform_none.xml ${DESTDIR}/etc/svc/profile/platform.xml
ln -s ns_dns.xml ${DESTDIR}/etc/svc/profile/name_service.xml
HNAME=`/usr/bin/hostname`
cat /etc/dumpadm.conf | sed s:${HNAME}:tribblix:g > ${DESTDIR}/etc/dumpadm.conf
mkdir -p ${DESTDIR}/var/crash/tribblix
chmod 0700 ${DESTDIR}/var/crash/tribblix

#
# sync up the overlays.
#
case `uname -p` in
i386)
	OVSRC="${THOME}/overlays.lx"
	;;
sparc)
	OVSRC="${THOME}/overlays.sparc"
	;;
esac
mkdir -p ${DESTDIR}/var/sadm/overlays
rm ${DESTDIR}/var/sadm/overlays/*.pkgs
rm ${DESTDIR}/var/sadm/overlays/*.ovl
cp ${OVSRC}/*.pkgs ${DESTDIR}/var/sadm/overlays
cp ${OVSRC}/*.ovl ${DESTDIR}/var/sadm/overlays

#
# make sure the install script is up to date
#
mkdir -p ${DESTDIR}/root
case `uname -p` in
i386)
	cp ${TBHOME}/live_install.sh ${DESTDIR}/root
	cp ${TBHOME}/over_install.sh ${DESTDIR}/root
	chmod a+x ${DESTDIR}/root/over_install.sh
	cp ${TBHOME}/format-a-disk.sh ${DESTDIR}/root
	cp ${TBHOME}/ufs_install.sh ${DESTDIR}/root
	;;
sparc)
	cp ${TBHOME}/live_install.sh.sparc ${DESTDIR}/root/live_install.sh
	cp ${TBHOME}/format-a-disk.sh.sparc ${DESTDIR}/root/format-a-disk.sh
	cp ${TBHOME}/ufs_install.sh.sparc ${DESTDIR}/root/ufs_install.sh
	;;
esac
chmod a+x ${DESTDIR}/root/live_install.sh
chmod a+x ${DESTDIR}/root/format-a-disk.sh
chmod a+x ${DESTDIR}/root/ufs_install.sh
cp ${TBHOME}/S99auto_install ${DESTDIR}/etc/rc2.d
chmod 755 ${DESTDIR}/etc/rc2.d/S99auto_install
echo "Fixing image"
${TBHOME}/install-fix $*

#
# copy support tools
#
rm -fr ${DESTDIR}/tools
mkdir ${DESTDIR}/tools
case `uname -p` in
i386)
	cp ${TBHOME}/setup-pxe-server ${DESTDIR}/tools
	cp ${TBHOME}/add-pxe-client ${DESTDIR}/tools
	;;
sparc)
	echo "WARNING: need to create sparc netinstall tools"
	;;
esac
chmod 755 ${DESTDIR}/tools/*

#
# create the zlib files
#
echo "Not creating solaris.zlib"
#${TBHOME}/mk-solaris-zlib $*
rm -f ${DESTDIR}/solaris.zlib
rm -f ${DESTDIR}/solarismisc.zlib
sync

#
# shuffle pieces out of the way to save space on the iso
# /usr comes from solaris.zlib, the others are in the ramdisk already
#
mkdir -p ${DESTTOP}/save
mv ${DESTDIR}/bin ${DESTTOP}/save
mv ${DESTDIR}/dev ${DESTTOP}/save
mv ${DESTDIR}/devices ${DESTTOP}/save
mv ${DESTDIR}/etc ${DESTTOP}/save
mv ${DESTDIR}/export ${DESTTOP}/save
mv ${DESTDIR}/home ${DESTTOP}/save
mv ${DESTDIR}/jack ${DESTTOP}/save
mv ${DESTDIR}/kernel ${DESTTOP}/save
mv ${DESTDIR}/lib ${DESTTOP}/save
mv ${DESTDIR}/mnt ${DESTTOP}/save
mv ${DESTDIR}/opt ${DESTTOP}/save
mv ${DESTDIR}/proc ${DESTTOP}/save
mv ${DESTDIR}/reconfigure ${DESTTOP}/save
mv ${DESTDIR}/root ${DESTTOP}/save
mv ${DESTDIR}/sbin ${DESTTOP}/save
mv ${DESTDIR}/system ${DESTTOP}/save
mv ${DESTDIR}/tmp ${DESTTOP}/save
mv ${DESTDIR}/usr ${DESTTOP}/save
mv ${DESTDIR}/var ${DESTTOP}/save
mv ${DESTDIR}/zonelib ${DESTTOP}/save
sync

#
# actually build the iso
#
${TBHOME}/create-lx-iso $*

#
# shuffle the files back so the image area is still valid
#
mv ${DESTTOP}/save/* ${DESTDIR}
