#!/bin/sh

THOME=${THOME:-/packages/localsrc/Tribblix}
DESTTOP=/export/tribblix
DESTDIR=${DESTTOP}/dist
RELEASE=28lx
NFLAG=""
QFLAG=""
OVFLAG=""

#
# flags
# -D desttop -> DESTTOP
# -N -> no install, dry run
# -O overlay -> install additional overlay
# -Q -> quiet, less output
# -R release string -> RELEASE
#
while getopts "D:NO:QR:" opt; do
    case $opt in
        D)
	    DESTTOP="$OPTARG"
	    DESTDIR=${DESTTOP}/dist
	    ;;
        N)
	    NFLAG="-N"
	    ;;
        O)
	    OVFLAG="${OVFLAG} -O $OPTARG"
	    ;;
        Q)
	    QFLAG="-Q"
	    ;;
        R)
	    RELEASE="$OPTARG"
	    ;;
    esac
done
shift $((OPTIND-1))

case $# in
    1)
	DESTDIR="${DESTDIR}.$1"
	;;
esac

TDIR=${THOME}/tribblix-build
case `uname -p` in
i386)
	$TDIR/install-lx-pkgs -D $DESTTOP $NFLAG $OVFLAG $QFLAG -R $RELEASE $*
	;;
*)
	echo "ERROR: unrecognized architecture for LX"
	exit 1
	;;
esac

if [ -z "${NFLAG}" ]; then
    if [ ! -f ${DESTDIR}/usr/bin/ls ]; then
	echo "ERROR: Package install failed!"
	exit 1
    fi
fi

case `uname -p` in
i386)
	$TDIR/mk-lx-pkgs-zap -D $DESTTOP $NFLAG $QFLAG -R $RELEASE $*
	;;
esac

if [ -n "${NFLAG}" ]; then
    echo "Dry run finished"
    exit 0
fi

if [ ! -f ${DESTDIR}/pkgs/catalog ]; then
    echo "ERROR: Extra packages failed!"
    exit 1
fi

$TDIR/build_iso -T lx -D $DESTTOP -R ${RELEASE} $*
