#!/bin/sh

THOME=${THOME:-/packages/localsrc/Tribblix}
DESTDIR=/export/tribblix/dist

case $# in
    1)
	DESTDIR="${DESTDIR}.$1"
	;;
esac

TDIR=${THOME}/tribblix-build
case `uname -p` in
sparc)
	$TDIR/install-pkgs.sparc $*
	;;
i386)
	$TDIR/install-pkgs $*
	;;
*)
	echo "ERROR: unrecognized architecture"
	exit 1
	;;
esac

if [ ! -f ${DESTDIR}/usr/bin/ls ]; then
    echo "ERROR: Package install failed!"
    exit 1
fi

case `uname -p` in
sparc)
	$TDIR/mk-pkgs-zap.sparc $*
	;;
i386)
	$TDIR/mk-pkgs-zap $*
	;;
esac

if [ ! -f ${DESTDIR}/pkgs/catalog ]; then
    echo "ERROR: Extra packages failed!"
    exit 1
fi

$TDIR/build_iso $*
