#!/bin/sh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

THOME=${THOME:-/packages/localsrc/Tribblix}
DESTTOP=/export/tribblix
DESTDIR=${DESTTOP}/dist
RELEASE=34lx
NFLAG=""
QFLAG=""
OVFLAG=""
MRSIZE="360m"

#
# flags
# -D desttop -> DESTTOP
# -M size -> MRSIZE, size of ramdisk
# -N -> no install, dry run
# -O overlay -> install additional overlay
# -Q -> quiet, less output
# -R release string -> RELEASE
#
while getopts "D:M:NO:QR:" opt; do
    case $opt in
        D)
	    DESTTOP="$OPTARG"
	    DESTDIR=${DESTTOP}/dist
	    ;;
        M)
	    MRSIZE="$OPTARG"
	    ;;
        N)
	    NFLAG="-N"
	    ;;
        O)
	    OVFLAG="${OVFLAG} -O $OPTARG"
	    ;;
        Q)
	    QFLAG="-Q"
	    ;;
        R)
	    RELEASE="$OPTARG"
	    ;;
    esac
done
shift $((OPTIND-1))

case $RELEASE in
    *lx*)
	:
	;;
    *)
	echo "ERROR: use make-dist for vanilla tribblix."
	exit 1
	;;
esac

case $# in
    1)
	DESTDIR="${DESTDIR}.$1"
	;;
esac

TDIR=${THOME}/tribblix-build
case `uname -p` in
i386)
	$TDIR/install-lx-pkgs -D $DESTTOP $NFLAG $OVFLAG $QFLAG -R $RELEASE $*
	;;
*)
	echo "ERROR: unrecognized architecture for LX"
	exit 1
	;;
esac

if [ -z "${NFLAG}" ]; then
    if [ ! -f ${DESTDIR}/usr/bin/ls ]; then
	echo "ERROR: Package install failed!"
	exit 1
    fi
fi

case `uname -p` in
i386)
	$TDIR/mk-lx-pkgs-zap -D $DESTTOP $NFLAG $QFLAG -R $RELEASE $*
	;;
esac

if [ -n "${NFLAG}" ]; then
    echo "Dry run finished"
    exit 0
fi

if [ ! -f ${DESTDIR}/pkgs/catalog ]; then
    echo "ERROR: Extra packages failed!"
    exit 1
fi

$TDIR/build_iso -T lx -D $DESTTOP -R ${RELEASE} -M "${MRSIZE}" $*
