#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2025 Peter Tribble
#

THOME=${THOME:-/packages/localsrc/Tribblix}
DESTTOP=/export/tribblix
DESTDIR=${DESTTOP}/dist
RELEASE=38
NFLAG=""
OVBASE="base-iso"
MRSIZE="340m"

#
# flags
# -D desttop -> DESTTOP
# -M size -> MRSIZE, size of ramdisk
# -N -> no install, dry run
# -R release string -> RELEASE
#
while getopts "D:M:NR:" opt; do
    case $opt in
        D)
	    DESTTOP="$OPTARG"
	    DESTDIR=${DESTTOP}/dist
	    ;;
        M)
	    MRSIZE="$OPTARG"
	    ;;
        N)
	    NFLAG="-N"
	    ;;
        R)
	    RELEASE="$OPTARG"
	    ;;
        *)
	    echo "Usage: $0 [-D destination] [-M size] [-N] [-R release]"
	    exit 2
	    ;;
    esac
done
shift $((OPTIND-1))

case $RELEASE in
    *lx*)
	echo "ERROR: use make-lx-dist for omnitribblix."
	exit 1
	;;
esac

case $# in
    1)
	DESTDIR="${DESTDIR}.$1"
	case $1 in
	    minimal)
		OVBASE="base-server"
		;;
	    ec2)
		OVBASE="base-cloud"
		;;
	esac
	;;
esac

TDIR=${THOME}/tribblix-build
case $(uname -p) in
sparc)
	"$TDIR/install-pkgs.sparc" -D "${DESTTOP}" $NFLAG -O "${OVBASE}" -R "${RELEASE}" "$@"
	;;
i386)
	"$TDIR/install-pkgs" -D "${DESTTOP}" $NFLAG -O "${OVBASE}" -R "${RELEASE}" "$@"
	;;
*)
	echo "ERROR: unrecognized architecture"
	exit 1
	;;
esac

if [ -z "${NFLAG}" ]; then
    if [ ! -f "${DESTDIR}/usr/bin/ls" ]; then
	echo "ERROR: Package install failed!"
	exit 1
    fi
fi

case $(uname -p) in
sparc)
	"$TDIR/mk-pkgs-zap.sparc" -D "${DESTTOP}" $NFLAG -R "${RELEASE}" "$@"
	;;
i386)
	"$TDIR/mk-pkgs-zap" -D "${DESTTOP}" $NFLAG -R "${RELEASE}" "$@"
	;;
esac

if [ -n "${NFLAG}" ]; then
    if [ ! -x /usr/bin/mkisofs ]; then
	echo "ERROR: mkisofs missing (install TRIBcdrtools)"
    fi
    echo "Dry run finished"
    exit 0
fi

if [ ! -f "${DESTDIR}/pkgs/catalog" ]; then
    echo "ERROR: Extra packages failed!"
    exit 1
fi

"$TDIR/build_iso" -D "${DESTTOP}" -R "${RELEASE}" -M "${MRSIZE}" "$@"
