#!/bin/sh

THOME=${THOME:-/packages/localsrc/Tribblix}
DESTDIR=/export/tribblix/dist

case $# in
    1)
	DESTDIR="${DESTDIR}.$1"
	;;
esac

TDIR=${THOME}/tribblix-build
case `uname -p` in
i386)
	$TDIR/install-lx-pkgs $*
	;;
*)
	echo "ERROR: unrecognized architecture for LX"
	exit 1
	;;
esac

if [ ! -d ${DESTDIR}/usr/bin/ls ]; then
    echo "ERROR: Package install failed!"
    exit 1
fi

case `uname -p` in
i386)
	$TDIR/mk-lx-pkgs-zap $*
	;;
esac

if [ ! -d ${DESTDIR}/pkgs/catalog ]; then
    echo "ERROR: Extra packages failed!"
    exit 1
fi

$TDIR/lx_iso $*
