#!/bin/sh
#
# copy packages into the pkgs folder on the iso, including all the packages
# necessary for the shipped overlays
#

DISTROOT=/export/tribblix/dist
ZAPDIR=${DISTROOT}/pkgs
THOME=/packages/localsrc/Tribblix
OIPKGDIR=${THOME}/oi-pkgs-0.8
IPKGDIR=${THOME}/illumos-pkgs-m14
VARIANT=""
OVDIR="overlays"

#
# Tribblix and illumos packages are explicitly versioned, we fake a version
# based on the current release for OI/OpenSXCE
#
RELVER="0.14"
OIVER="0.8o"
ILVER="${RELVER}.0"

case $# in
1)
	DISTROOT=${DISTROOT}.$1
	ZAPDIR=${DISTROOT}/pkgs
	VARIANT=$1
	;;
esac

TFILE="/tmp/mkzap.$$"
rm -fr ${TFILE}
touch $TFILE
for opkg in `cat ${THOME}/${OVDIR}/overlays.iso`
do
    if [ -f ${THOME}/${OVDIR}/${opkg}.pkgs.${VARIANT} ]; then
	cat ${THOME}/${OVDIR}/${opkg}.pkgs.${VARIANT} >> $TFILE
    else
	cat ${THOME}/${OVDIR}/${opkg}.pkgs >> $TFILE
    fi
done

#
# we look in ${THOME}/pkgs, then ${IPKGDIR}/pkgs and ${OIPKGDIR}/pkgs
#
#
# verify first
#
VALID=yes
ERRLIST=""
for ipkg in `cat ${TFILE}|sort|uniq`
do
  THISVER="XXX"
  PKGI=${THOME}/build/${ipkg}/pkginfo
  if [ -f ${PKGI} ]; then
      THISVER=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI | sed 's="==g'`
  fi
  if [ -f ${THOME}/pkgs/${ipkg}.${THISVER}.zap ]; then
      echo "Installing $ipkg ${THISVER} from Tribblix"
  elif [ -f ${IPKGDIR}/pkgs/${ipkg}.${ILVER}.zap ]; then
      echo "Installing $ipkg from Illumos"
  elif [ -f ${OIPKGDIR}/pkgs/${ipkg}.${OIVER}.zap ]; then
      echo "Installing $ipkg from OpenIndiana"
  else
      echo "ERROR: package $ipkg not found"
      VALID=no
      ERRLIST="$ERRLIST $ipkg"
  fi
done
if [ "X$VALID" = "Xno" ]; then
    echo "ERROR: missing packages, mk-pkgs-zap aborted"
    echo "Missing: $ERRLIST"
    rm -f $TFILE
    exit 1
fi

#
# delete the pkgs directory to avoid lingering leftovers
#
rm -fr $ZAPDIR
mkdir -p $ZAPDIR
if [ ! -d $SZAPDIR ]; then
    echo "ERROR: unable to create $ZAPDIR"
    rm -f $TFILE
    exit 1
fi
rm -f ${ZAPDIR}/catalog
touch ${ZAPDIR}/catalog
chmod 644 ${ZAPDIR}/catalog

#
# use pre-existing zap files
#
for ipkg in `cat ${TFILE}|sort|uniq`
do
  if [ -f ${DISTROOT}/var/sadm/pkg/${ipkg}/pkginfo ]; then
      echo "Skipping installed ${ipkg}"
  else
      THISVER="XXX"
      PKGI=${THOME}/build/${ipkg}/pkginfo
      if [ -f ${PKGI} ]; then
	  THISVER=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI | sed 's="==g'`
      fi
      if [ -f ${THOME}/pkgs/${ipkg}.${THISVER}.zap ]; then
	  cp ${THOME}/pkgs/${ipkg}.${THISVER}.zap $ZAPDIR
      elif [ -f ${IPKGDIR}/pkgs/${ipkg}.${ILVER}.zap ]; then
	  cp ${IPKGDIR}/pkgs/${ipkg}.${ILVER}.zap ${ZAPDIR}/${ipkg}.${ILVER}.zap
	  THISVER=${ILVER}
      else
	  cp ${OIPKGDIR}/pkgs/${ipkg}.${OIVER}.zap ${ZAPDIR}/${ipkg}.${OIVER}.zap
	  THISVER=${OIVER}
      fi
      echo "${ipkg}|${THISVER}|"`${DISTROOT}/usr/lib/zap/pkgdepend ${ZAPDIR}/${ipkg}.${THISVER}.zap` >> ${ZAPDIR}/catalog
  fi
done

rm -f $TFILE

#
# preload package catalogs and aliases
#
cd ${THOME}/build
./create-catalog > ${DISTROOT}/etc/zap/repositories/tribblix.catalog
./create-oi-catalog > ${DISTROOT}/etc/zap/repositories/oi.catalog
./create-illumos-catalog > ${DISTROOT}/etc/zap/repositories/illumos.catalog
./create-aliases > ${DISTROOT}/etc/zap/repositories/tribblix.aliases
./create-oi-aliases > ${DISTROOT}/etc/zap/repositories/oi.aliases
./create-illumos-aliases > ${DISTROOT}/etc/zap/repositories/illumos.aliases

#
# preload overlay catalog
#
cd ${THOME}/${OVDIR}
${THOME}/build/create-overlay-catalog > ${DISTROOT}/etc/zap/repositories/tribblix.overlays

#
# show the space used
#
sync
/usr/bin/du -hds $ZAPDIR
