#!/bin/sh
#
# copy packages into the pkgs folder on the iso, including all the packages
# necessary for the shipped overlays
#

RELEASE=23.1

DISTROOT=/export/tribblix/dist
ZAPDIR=${DISTROOT}/pkgs
THOME=${THOME:-/packages/localsrc/Tribblix}
TPKGDIR=${THOME}/pkgs
EXTRAPKGDIR=${THOME}/repo-master/oi-151a9
IPKGDIR=${THOME}/illumos-pkgs-m${RELEASE}/pkgs
VARIANT=""
OVDIR="overlays"

#
# Tribblix and illumos packages are explicitly versioned, we fake a version
# based on the current release for OI/OpenSXCE
#
EXTRAVER="0.9o"
ILVER="0.${RELEASE}"

#
# the one argument is a variant, which sets the destination directory
#
# if there's a variant overlays.iso, then use that
#
OVLIST=${THOME}/${OVDIR}/overlays.iso
case $# in
1)
	DISTROOT=${DISTROOT}.$1
	ZAPDIR=${DISTROOT}/pkgs
	VARIANT=$1
	if [ -f ${THOME}/${OVDIR}/overlays.${VARIANT}.iso ]; then
	    OVLIST=${THOME}/${OVDIR}/overlays.${VARIANT}.iso
	fi
	;;
esac

TFILE="/tmp/mkzap.$$"
rm -fr ${TFILE}
touch $TFILE
for opkg in `cat ${OVLIST}`
do
    if [ -f ${THOME}/${OVDIR}/${opkg}.pkgs.${VARIANT} ]; then
	cat ${THOME}/${OVDIR}/${opkg}.pkgs.${VARIANT} >> $TFILE
    else
	cat ${THOME}/${OVDIR}/${opkg}.pkgs >> $TFILE
    fi
done

#
# we look in ${TPKGDIR}, then ${IPKGDIR} and ${EXTRAPKGDIR}
#
#
# verify first
#
VALID=yes
ERRLIST=""
for ipkg in `cat ${TFILE}|sort|uniq|egrep -v '^(TRIBzap|TRIBzap-upgrade|TRIBrelease-name)$'`
do
  THISVER="XXX"
  PKGI=${THOME}/build/${ipkg}/pkginfo
  if [ -f ${PKGI} ]; then
      THISVER=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI | sed 's="==g'`
  fi
  if [ -f ${TPKGDIR}/${ipkg}.${THISVER}.zap ]; then
      echo "Installing $ipkg ${THISVER} from Tribblix"
  elif [ -f ${IPKGDIR}/${ipkg}.${ILVER}.zap ]; then
      echo "Installing $ipkg from Illumos"
  elif [ -f ${EXTRAPKGDIR}/${ipkg}.${EXTRAVER}.zap ]; then
      echo "Installing $ipkg from OpenIndiana"
  else
      echo "ERROR: package $ipkg not found"
      VALID=no
      ERRLIST="$ERRLIST $ipkg"
  fi
done
if [ "X$VALID" = "Xno" ]; then
    echo "ERROR: missing packages, mk-pkgs-zap aborted"
    echo "Missing: $ERRLIST"
    rm -f $TFILE
    exit 1
fi

#
# delete the pkgs directory to avoid lingering leftovers
#
rm -fr $ZAPDIR
mkdir -p $ZAPDIR
if [ ! -d $SZAPDIR ]; then
    echo "ERROR: unable to create $ZAPDIR"
    rm -f $TFILE
    exit 1
fi
rm -f ${ZAPDIR}/catalog
touch ${ZAPDIR}/catalog
chmod 644 ${ZAPDIR}/catalog

#
# use pre-existing zap files
#
for ipkg in `cat ${TFILE}|sort|uniq|egrep -v '^(TRIBzap|TRIBzap-upgrade|TRIBrelease-name)$'`
do
  if [ -f ${DISTROOT}/var/sadm/pkg/${ipkg}/pkginfo ]; then
      echo "Skipping installed ${ipkg}"
  else
      THISVER="XXX"
      PKGI=${THOME}/build/${ipkg}/pkginfo
      if [ -f ${PKGI} ]; then
	  THISVER=`awk -F= '{if ($1 == "VERSION") print $2}' $PKGI | sed 's="==g'`
      fi
      if [ -f ${TPKGDIR}/${ipkg}.${THISVER}.zap ]; then
	  cp ${TPKGDIR}/${ipkg}.${THISVER}.zap $ZAPDIR
      elif [ -f ${IPKGDIR}/${ipkg}.${ILVER}.zap ]; then
	  cp ${IPKGDIR}/${ipkg}.${ILVER}.zap ${ZAPDIR}/${ipkg}.${ILVER}.zap
	  THISVER=${ILVER}
      else
	  cp ${EXTRAPKGDIR}/${ipkg}.${EXTRAVER}.zap ${ZAPDIR}/${ipkg}.${EXTRAVER}.zap
	  THISVER=${EXTRAVER}
      fi
      echo "${ipkg}|${THISVER}|"`${DISTROOT}/usr/lib/zap/pkgdepend ${ZAPDIR}/${ipkg}.${THISVER}.zap` >> ${ZAPDIR}/catalog
  fi
done

rm -f $TFILE

#
# preload package catalogs and aliases
#
cd ${THOME}/build
if [ -f ${TPKGDIR}/catalog ]; then
    cp ${TPKGDIR}/catalog ${DISTROOT}/etc/zap/repositories/tribblix.catalog
else
    ./create-catalog ${TPKGDIR} > ${DISTROOT}/etc/zap/repositories/tribblix.catalog
fi
if [ -f ${EXTRAPKGDIR}/catalog ]; then
    cp ${EXTRAPKGDIR}/catalog ${DISTROOT}/etc/zap/repositories/oi.catalog
else
    ./create-oi-catalog > ${DISTROOT}/etc/zap/repositories/oi.catalog
fi
if [ -f ${IPKGDIR}/catalog ]; then
    cp ${IPKGDIR}/catalog ${DISTROOT}/etc/zap/repositories/illumos.catalog
else
    ./create-illumos-catalog ${IPKGDIR} > ${DISTROOT}/etc/zap/repositories/illumos.catalog
fi
if [ -f ${TPKGDIR}/aliases ]; then
    cp ${TPKGDIR}/aliases ${DISTROOT}/etc/zap/repositories/tribblix.aliases
else
    ./create-aliases ${TPKGDIR} > ${DISTROOT}/etc/zap/repositories/tribblix.aliases
fi
if [ -f ${EXTRAPKGDIR}/aliases ]; then
    cp ${EXTRAPKGDIR}/aliases ${DISTROOT}/etc/zap/repositories/oi.aliases
else
    ./create-oi-aliases > ${DISTROOT}/etc/zap/repositories/oi.aliases
fi
if [ -f ${IPKGDIR}/aliases ]; then
    cp ${IPKGDIR}/aliases ${DISTROOT}/etc/zap/repositories/illumos.aliases
else
    ./create-illumos-aliases ${IPKGDIR} > ${DISTROOT}/etc/zap/repositories/illumos.aliases
fi

#
# preload overlay catalog
#
cd ${THOME}/${OVDIR}
if [ -f catalog ]; then
    cp catalog ${DISTROOT}/etc/zap/repositories/tribblix.overlays
else
    ${THOME}/build/create-overlay-catalog > ${DISTROOT}/etc/zap/repositories/tribblix.overlays
fi

#
# show the space used
#
sync
/usr/bin/du -hds $ZAPDIR
