#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2024 Peter Tribble
#

#
# create the solaris.zlib file
#

DESTDIR=/export/tribblix/dist
CLEVEL="gzip"

case $# in
1)
	DESTDIR=${DESTDIR}.$1
	;;
esac

cd ${DESTDIR}

#
# ought to investigate sorting
#
SORT_OPTION=""
mkisofs -o solaris.zlib $SORT_OPTION -quiet -N -l -R \
    -U -allow-multidot -no-iso-translate -cache-inodes \
    -d -D -V "compress" usr
ls -lh solaris.zlib
lofiadm -C ${CLEVEL} solaris.zlib
ls -lh solaris.zlib
