#!/bin/sh
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# }}}
#
# Copyright 2023 Peter Tribble
#

#
# if an install configuration exists, install according to that profile
#

case $1 in
start)
IPROFILE=`/sbin/devprop install_profile`
if [ ! -z "$IPROFILE" ]; then
  echo "PLEASE WAIT" | tee /dev/msglog
  echo "Automatically installing Tribblix" | tee /dev/msglog
  echo "Install profile is $IPROFILE" | tee /dev/msglog
  /root/live_install.sh | tee /dev/msglog
fi
;;
esac
