#!/bin/ksh
#
# takes an iso image and puts the pieces in the right place for pxe
# installation
#

#
# needs to be told:
#  - what the tftp root is
#  - where the htdocs directory is
#  - what the URL of the server is
#

#
# FIXME needs progress feedback
#
umask 022
DEBUG=""

usage() {
  echo "Usage: $0 -t tftp_dir -h htdocs_dir -u http_url"
  exit 1
}

#
# interactive argument handling
#
TFTPBOOT="/tftpboot"
TFTPDIR=""
HTDOCS=""
URL=""
while getopts "t:h:u:" opt; do
  case $opt in
    t)
      TFTPDIR="$OPTARG"
      ;;
    h)
      HTDOCS="$OPTARG"
      ;;
    u)
      URL="$OPTARG"
      ;;
    esac
done
shift $((OPTIND-1))

case $# in
0)
  printf ""
  ;;
*)
  usage
  ;;
esac

#
# check everything is defined
#
if [ -z "$TFTPDIR" ]; then
  echo "TFTP directory must be defined"
  usage
fi
if [ -z "$HTDOCS" ]; then
  echo "HTDOCS directory must be defined"
  usage
fi
if [ -z "$URL" ]; then
  echo "Server URL must be defined"
  usage
fi

#
# check the right things exist
#
if [ ! -d ${TFTPBOOT} ]; then
  echo "Unable to find ${TFTPBOOT}"
  usage
fi
if [ -f $HTDOCS ]; then
  echo "The HTDOCS location must be a directory"
  usage
fi
if [ -d $HTDOCS ]; then
  NF=`/bin/ls -1 $HTDOCS | wc -l | awk '{print $1}'`
case $NF in
0)
  printf ""
  ;;
*)
  echo "The HTDOCS location must be empty"
  usage
  ;;
esac
fi
case $URL in
http://*)
  printf ""
  ;;
*)
  echo "Unable to recognize URL format"
  usage
  ;;
esac
HTTOP=`dirname $HTDOCS`
if [ ! -d $HTTOP ]; then
  echo "Unable to find parent of HTDOCS directory"
  usage
fi

#
# everything exists, check that tftp is configured
#
if [ ! -d ${TFTPBOOT} ]; then
  echo "Unable to find ${TFTPBOOT} - is tftp configured?"
  exit 2
fi
if [ -d ${TFTPBOOT}/${TFTPDIR} ]; then
  echo "TFTP location ${TFTPDIR} already exists"
  exit 2
fi
TSTATE=`/usr/bin/svcs -H tftp/udp6 | awk '{print $1}'`
case $TSTATE in
online)
  printf ""
  ;;
disabled)
  echo "Enabling tftp service"
  $DEBUG /usr/sbin/svcadm enable tftp/udp6
  ;;
*)
  echo "Cannot find tftp service"
  exit 2
  ;;
esac

#
# FIXME need to resolve the path to the script
#
# we're in the ISO, so need to check we have
#  grub
#  platform
#  pkgs
#  solaris.zlib
#
if [ ! -d pkgs ]; then
  echo "Unable to find pkgs"
  exit 2
fi
if [ ! -d platform ]; then
  echo "Unable to find the platform directory"
  exit 2
fi
if [ ! -d boot ]; then
  echo "Unable to find the iso boot directory"
  exit 2
fi
if [ ! -f boot/grub/pxegrub ]; then
  echo "Unable to find pxegrub"
  exit 2
fi
if [ ! -f platform/i86pc/boot_archive ]; then
  echo "Unable to find the boot archive"
  exit 2
fi
if [ ! -f platform/i86pc/kernel/unix ]; then
  if [ ! -f platform/i86pc/kernel/amd64/unix ]; then
    echo "Unable to find the kernel"
    exit 2
  fi
fi
if [ ! -f solaris.zlib ]; then
  echo "Unable to find solaris.zlib"
  exit 2
fi

#
# all seems to be present
#
$DEBUG mkdir -p $HTDOCS
echo "Copying packages"
$DEBUG cp -r pkgs $HTDOCS
echo "Copying solaris.zlib"
$DEBUG cp solaris.zlib $HTDOCS
echo "Copying files to tftp server"
$DEBUG mkdir -p ${TFTPBOOT}/$TFTPDIR/platform/i86pc/kernel/amd64
$DEBUG cp boot/grub/pxegrub ${TFTPBOOT}/$TFTPDIR
$DEBUG cp platform/i86pc/boot_archive ${TFTPBOOT}/$TFTPDIR/platform/i86pc
chmod a+r ${TFTPBOOT}/$TFTPDIR/platform/i86pc/boot_archive
if [ -f platform/i86pc/kernel/unix ]; then
  $DEBUG cp platform/i86pc/kernel/unix ${TFTPBOOT}/$TFTPDIR/platform/i86pc/kernel
  chmod a+rx ${TFTPBOOT}/$TFTPDIR/platform/i86pc/kernel/unix
fi
if [ -f platform/i86pc/kernel/amd64/unix ]; then
  $DEBUG cp platform/i86pc/kernel/amd64/unix ${TFTPBOOT}/$TFTPDIR/platform/i86pc/kernel/amd64
  chmod a+rx ${TFTPBOOT}/$TFTPDIR/platform/i86pc/kernel/amd64/unix
fi

#
# we copy the add-pxe-client script to the tftp location
# and create a file containing the locations that are in use
#
$DEBUG cp tools/add-pxe-client ${TFTPBOOT}/$TFTPDIR

save_config() {
echo tftpboot=${TFTPBOOT}
echo tftpdir=${TFTPBOOT}/$TFTPDIR
echo install_media=${URL}/
echo htdocs=$HTDOCS
echo install_pkgs=${URL}/pkgs/
}

if [ -n "$DEBUG" ]; then
  save_config
else
  save_config > ${TFTPBOOT}/$TFTPDIR/cardigan.cfg
fi

echo "To add pxe clients, cd to ${TFTPBOOT}/$TFTPDIR"
echo "and run the add-pxe-client script in that directory"
