#!/bin/sh
#
# perform an illumos debug build
# with -q, do a quick build (no shadows)
#
# assumes we're doing development of illumos-gate
# won't work for illumos-omnios
#

THOME=${THOME:-/packages/localsrc/Tribblix}
export THOME

ILLSH=illumos.sh.debug
ARCH=`uname -p`

case $1 in
    -q)
	ILLSH=illumos.sh.quickdebug
	;;
esac

#
# allow override
#
if [ -f ../${ILLSH} ]; then
    ILLSH="../${ILLSH}"
else
    ILLSH="${THOME}/tribblix-build/illumos/${ILLSH}"
fi

echo "Build using $ILLSH"

if [ ! -f usr/src/tools/scripts/nightly ]; then
    echo "Cannot find nightly, are you in a gate?"
    exit 1
fi

if [ ! -f ../on-closed-bins.${ARCH}.tar.bz2 ]; then
    echo "Cannot find closed-bins"
    exit 1
fi

if [ ! -f ../on-closed-bins-nd.${ARCH}.tar.bz2 ]; then
    echo "Cannot find closed-bins-nd"
    exit 1
fi

if [ ! -f ${ILLSH} ]; then
    echo "Cannot find ${ILLSH}"
    exit 1
fi

if [ ! -f ${THOME}/tribblix-build/illumos/Makefile.auditrecord ]; then
    echo "Cannot find auditrecord Makefile"
    exit 1
fi

#
# environment sanity check
#
if [ ! -f ${THOME}/tribblix-build/illumos/check-environment.sh ]; then
    echo "ERROR: cannot check enviromnent"
    echo "Looking for ${THOME}/tribblix-build/illumos/check-environment.sh"
    exit 1
fi
if [ ! -x ${THOME}/tribblix-build/illumos/check-environment.sh ]; then
    echo "ERROR: cannot check enviromnent"
    echo "${THOME}/tribblix-build/illumos/check-environment.sh is not executable"
    exit 1
fi
${THOME}/tribblix-build/illumos/check-environment.sh
if [ $? -ne 0 ]; then
    echo "Environment check failed, aborting"
    exit 1
fi

#
# everything appears to be in place
#
echo "Unpacking closed-bins"
bzcat ../on-closed-bins.${ARCH}.tar.bz2 | tar xf -
echo "Unpacking closed-bins-nd"
bzcat ../on-closed-bins-nd.${ARCH}.tar.bz2 | tar xf -
echo "Copying files"
cp ${ILLSH} illumos.sh

#
# changes to the gate
#
rm -f usr/src/cmd/auditrecord/Makefile
cp ${THOME}/tribblix-build/illumos/Makefile.auditrecord usr/src/cmd/auditrecord/Makefile
if [ ! -f usr/src/cmd/auditrecord/Makefile ]; then
    echo "Oops, copying auditrecord Makefile failed"
    exit 2
fi
for file in ${THOME}/tribblix-build/illumos/*.patch
do
    gpatch -p1 < $file
done

#
# and kaboom
#
echo "Starting build"
/bin/date
time usr/src/tools/scripts/nightly illumos.sh
/bin/date

ls -l log/latest/mail_msg
